// <auto-generated />
using DesafioAxisRefactor.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DesafioAxisRefactor.Infrastructure.Migrations
{
    [DbContext(typeof(DesafioAxisRefactorContext))]
    [Migration("20231017211257_cooperador-cooperativas2")]
    partial class cooperadorcooperativas2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DesafioAxisRefactor.Domain.Models.Cooperado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContaCorrente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CooperativasId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CooperativasId");

                    b.ToTable("Cooperado");
                });

            modelBuilder.Entity("DesafioAxisRefactor.Domain.Models.Cooperativas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("cooperativas");
                });

            modelBuilder.Entity("DesafioAxisRefactor.Domain.Models.Cooperado", b =>
                {
                    b.HasOne("DesafioAxisRefactor.Domain.Models.Cooperativas", "Cooperativas")
                        .WithMany("Cooperados")
                        .HasForeignKey("CooperativasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cooperativas");
                });

            modelBuilder.Entity("DesafioAxisRefactor.Domain.Models.Cooperativas", b =>
                {
                    b.Navigation("Cooperados");
                });
#pragma warning restore 612, 618
        }
    }
}
